import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFD1D1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  accountsButton: {
    backgroundColor: '#eee',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginTop: 8,
  },
  actionCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FF5A4D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchInput: {
    backgroundColor: '#F3F3F3',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 8,
  },
  txBox: {
    backgroundColor: '#F3F3F3',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    position: 'relative',
  },
  txSend: {
    borderLeftWidth: 6,
    borderLeftColor: '#D7263D',
  },
  txReceive: {
    borderLeftWidth: 6,
    borderLeftColor: '#4CAF50',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.01)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    minHeight: 400,
    alignItems: 'stretch',
  },
  searchButton: {
    position: 'absolute',
    right: 12,
    top: 12,
  },
  input: {
    backgroundColor: '#F3F3F3',
    borderRadius: 6,
    padding: 14,
    fontSize: 16,
    color: '#222',
  },
  button: {
    backgroundColor: '#D7263D',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#D7263D',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  signupButton: {
    width: '100%',
    backgroundColor: '#FF5A4D',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 20,
  },
  signupButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  // Settings styles
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#D7263D',
    marginBottom: 12,
    letterSpacing: 2,
  },
  settingsGroup: {
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  settingsText: {
    fontSize: 16,
    color: '#222',
  },
  container: {
    padding: 24,
    paddingTop: 60,
  },
  section: {
    marginBottom: 32,
  },
  logoutButton: {
    backgroundColor: '#D7263D',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  logoutButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  deleteButton: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D7263D',
  },
  deleteButtonText: {
    color: '#D7263D',
    fontWeight: 'bold',
    fontSize: 16,
  },
  versionText: {
    color: '#888',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 8,
  },
  label: {
    fontSize: 16,
    color: '#222',
    marginBottom: 8,
  },
  notValidContainer: {
    backgroundColor: '#fff',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: '90%',
    maxWidth: 400,
    marginTop: 40,
  },
  notValidTitle: {
    color: '#D7263D',
    fontWeight: 'bold',
    fontSize: 24,
    marginBottom: 16,
  },
  notValidText: {
    color: '#666',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 24,
  },
  retryButton: {
    backgroundColor: '#D7263D',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
});

export default styles; 